"""Job matching engine (Phase 5).

Numeric sub-scores are computed deterministically (technical uses local embeddings for
semantic similarity); the human-readable reasoning is generated by local Qwen3 with a
deterministic fallback. Eligibility from Phase 4 hard-maps NOT_ELIGIBLE -> DO_NOT_APPLY.
"""

from __future__ import annotations

import math

from app.ai.base import AIProvider
from app.ai.exceptions import AIProviderError
from app.models.candidate_profile import CandidateProfile
from app.models.job import Job
from app.schemas.job_analysis import (
    Eligibility,
    JobAnalysisResult,
    Region,
    SponsorshipUS,
    VisaSupportEU,
)
from app.schemas.matching import (
    MatchResult,
    MatchScores,
    MatchWeights,
    Recommendation,
)

SKILL_SIMILARITY_THRESHOLD = 0.70
APPLY_THRESHOLD = 75.0
REVIEW_THRESHOLD = 55.0
LOW_PRIORITY_THRESHOLD = 35.0


def cosine(a: list[float], b: list[float]) -> float:
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


def _mean_vector(vectors: list[list[float]]) -> list[float]:
    if not vectors:
        return []
    length = len(vectors[0])
    return [sum(v[i] for v in vectors) / len(vectors) for i in range(length)]


def technical_match(
    provider: AIProvider,
    candidate_skills: list[str],
    job_skills: list[str],
    candidate_text: str,
    job_text: str,
    threshold: float = SKILL_SIMILARITY_THRESHOLD,
) -> tuple[float, list[str], list[str]]:
    """Return (score 0-100, matched job skills, missing job skills)."""
    matched: list[str] = []
    missing: list[str] = []

    if job_skills:
        cand = [(s, provider.embed(s)) for s in candidate_skills]
        jobs = [(s, provider.embed(s)) for s in job_skills]
        cand_lower = {s.lower() for s in candidate_skills}
        for name, jv in jobs:
            best = max((cosine(jv, cv) for _, cv in cand), default=0.0)
            if name.lower() in cand_lower or best >= threshold:
                matched.append(name)
            else:
                missing.append(name)
        coverage = len(matched) / len(jobs)
        sim = (
            cosine(_mean_vector([v for _, v in jobs]), _mean_vector([v for _, v in cand]))
            if cand
            else 0.0
        )
        score = 100.0 * (0.6 * coverage + 0.4 * max(0.0, sim))
    elif candidate_text.strip() and job_text.strip():
        sim = cosine(provider.embed(candidate_text), provider.embed(job_text))
        score = 100.0 * max(0.0, min(1.0, sim))
    else:
        score = 50.0

    return round(score, 1), matched, missing


def experience_score(candidate_years: float | None, required_min: int | None) -> float:
    if required_min is None:
        return 70.0
    if candidate_years is None:
        return 50.0
    if candidate_years >= required_min:
        return 100.0
    return max(0.0, 100.0 - (required_min - candidate_years) * 15.0)


def sponsorship_score(analysis: JobAnalysisResult) -> float:
    if analysis.citizenship_required or analysis.security_clearance_required:
        return 0.0
    us_map = {
        SponsorshipUS.SPONSORSHIP_EXPLICIT: 100.0,
        SponsorshipUS.SPONSORSHIP_LIKELY: 80.0,
        SponsorshipUS.SPONSORSHIP_UNCLEAR: 50.0,
        SponsorshipUS.SPONSORSHIP_UNLIKELY: 30.0,
        SponsorshipUS.NO_SPONSORSHIP: 0.0,
        SponsorshipUS.WORK_AUTH_REQUIRED: 0.0,
    }
    eu_map = {
        VisaSupportEU.VISA_SUPPORT_EXPLICIT: 100.0,
        VisaSupportEU.VISA_SUPPORT_LIKELY: 80.0,
        VisaSupportEU.VISA_SUPPORT_UNCLEAR: 50.0,
        VisaSupportEU.VISA_SUPPORT_UNLIKELY: 30.0,
        VisaSupportEU.NO_VISA_SUPPORT: 0.0,
        VisaSupportEU.EU_WORK_AUTH_REQUIRED: 0.0,
    }
    if analysis.region is Region.USA and analysis.sponsorship_us is not None:
        return us_map.get(analysis.sponsorship_us, 50.0)
    if analysis.region is Region.EUROPE and analysis.visa_support_eu is not None:
        return eu_map.get(analysis.visa_support_eu, 50.0)
    return 50.0


def location_score(profile: CandidateProfile, analysis: JobAnalysisResult) -> float:
    region = analysis.region.value
    if analysis.relocation.value == "REMOTE" and profile.open_to_remote:
        return 100.0
    if region in (profile.preferred_regions or []):
        return 100.0
    if analysis.region is Region.UNKNOWN:
        return 60.0
    if profile.open_to_relocation:
        return 70.0
    return 40.0


def language_score(profile: CandidateProfile, analysis: JobAnalysisResult) -> float:
    comp = analysis.english_compatibility.value
    if comp == "ENGLISH_OK":
        return 100.0
    if comp == "OTHER_LANGUAGE_REQUIRED":
        # We can't know which language; treat as a concern unless multilingual.
        return 60.0 if len(profile.languages or []) > 1 else 40.0
    return 70.0


def relocation_score(profile: CandidateProfile, analysis: JobAnalysisResult) -> float:
    rel = analysis.relocation.value
    if rel == "REMOTE":
        return 100.0
    if rel == "RELOCATION_SUPPORTED":
        return 90.0
    if rel == "RELOCATION_REQUIRED":
        return 100.0 if profile.open_to_relocation else 20.0
    if rel == "ONSITE_NO_RELOCATION":
        return 60.0 if profile.open_to_relocation else 40.0
    return 70.0  # NOT_MENTIONED


def overall(scores: MatchScores, weights: MatchWeights) -> float:
    total = (
        scores.technical * weights.technical
        + scores.experience * weights.experience
        + scores.sponsorship * weights.sponsorship
        + scores.location * weights.location
        + scores.language * weights.language
        + scores.relocation * weights.relocation
    )
    denom = (
        weights.technical
        + weights.experience
        + weights.sponsorship
        + weights.location
        + weights.language
        + weights.relocation
    )
    return round(total / denom if denom else 0.0, 1)


def recommend(eligibility: Eligibility, overall_score: float) -> Recommendation:
    if eligibility is Eligibility.NOT_ELIGIBLE:
        return Recommendation.DO_NOT_APPLY
    if overall_score >= APPLY_THRESHOLD:
        return Recommendation.APPLY
    if overall_score >= REVIEW_THRESHOLD:
        return Recommendation.REVIEW
    if overall_score >= LOW_PRIORITY_THRESHOLD:
        return Recommendation.LOW_PRIORITY
    return Recommendation.DO_NOT_APPLY


def _fallback_reasoning(
    scores: MatchScores, rec: Recommendation, matched: list[str], missing: list[str]
) -> str:
    return (
        f"Recommendation {rec.value}. Technical {scores.technical}, experience "
        f"{scores.experience}, sponsorship {scores.sponsorship}, location "
        f"{scores.location}. Matched skills: {', '.join(matched) or 'none'}. "
        f"Missing: {', '.join(missing) or 'none'}."
    )


def _ai_reasoning(
    provider: AIProvider,
    job: Job,
    scores: MatchScores,
    rec: Recommendation,
    matched: list[str],
    missing: list[str],
) -> str:
    prompt = (
        f"In 2-3 sentences, explain this job-match recommendation for a candidate who "
        f"needs visa sponsorship. Job: {job.title} at {job.company}. "
        f"Scores (0-100): technical={scores.technical}, experience={scores.experience}, "
        f"sponsorship={scores.sponsorship}, location={scores.location}, "
        f"language={scores.language}, relocation={scores.relocation}. "
        f"Recommendation: {rec.value}. Matched skills: {matched}. Missing: {missing}. "
        f"Do not invent facts or promise a visa."
    )
    try:
        text = provider.generate(prompt)
        return text.strip() or _fallback_reasoning(scores, rec, matched, missing)
    except AIProviderError:
        return _fallback_reasoning(scores, rec, matched, missing)


def match_job(
    provider: AIProvider,
    profile: CandidateProfile,
    job: Job,
    analysis: JobAnalysisResult,
    eligibility: Eligibility,
    weights: MatchWeights | None = None,
) -> MatchResult:
    weights = weights or MatchWeights()

    candidate_text = " ".join(
        [profile.headline or "", " ".join(profile.skills or [])]
    ).strip()
    job_text = " ".join([job.title or "", job.description or ""]).strip()

    tech, matched, missing = technical_match(
        provider,
        profile.skills or [],
        analysis.technical_skills,
        candidate_text,
        job_text,
    )

    scores = MatchScores(
        technical=tech,
        experience=experience_score(
            profile.years_experience, analysis.experience_years_min
        ),
        sponsorship=sponsorship_score(analysis),
        location=location_score(profile, analysis),
        language=language_score(profile, analysis),
        relocation=relocation_score(profile, analysis),
    )
    overall_score = overall(scores, weights)
    rec = recommend(eligibility, overall_score)

    concerns = list(analysis.concerns)
    if rec is Recommendation.DO_NOT_APPLY and eligibility is Eligibility.NOT_ELIGIBLE:
        note = "Not eligible (citizenship / no sponsorship) — do not apply."
        if note not in concerns:
            concerns.insert(0, note)

    reasoning = _ai_reasoning(provider, job, scores, rec, matched, missing)

    return MatchResult(
        scores=scores,
        overall_score=overall_score,
        recommendation=rec,
        reasoning=reasoning,
        matched_skills=matched,
        missing_skills=missing,
        sponsorship_evidence=analysis.sponsorship_evidence,
        concerns=concerns,
        weights=weights,
    )
